version: '3.7'

services:
#  productiumdb:
#      image: postgres:12.1-alpine
#      restart: unless-stopped
#      container_name: productiumdb
#      environment:
#        - POSTGRES_HOST=${POSTGRES_HOST}
#        - POSTGRES_USER=${POSTGRES_USER}
#        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#        - POSTGRES_DATABASE=${POSTGRES_DATABASE}
#      ports:
#        - 5432:5432
#      expose:
#        - 5432
#      volumes:
#        - pgdata:/var/lib/postgresql/data
#      networks:
#        productiumdb: {}

  productiumback:
    image: productiumback
    restart: unless-stopped
    container_name: productiumback
    build: .
    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - ${SERVER_PORT}:${SERVER_PORT}
    - 9223:9223
    expose:
    - 5432
    command: npm run start:prod
    env_file:
    - .env
    networks:
      productiumdb: {}
#    depends_on:
#    - productiumdb

networks:
  productiumdb:
    driver: bridge

#volumes:
#  pgdata: